vich_uploader:
    db_driver: orm

    mappings:
        voyage_img:
            uri_prefix: /img/voyage
            upload_destination: '%kernel.project_dir%/public/img/voyage'
            #delete_on_remove: false
